name = "macro"
compatibility_date = "2026-02-27"
workers_dev = true
main = "worker.js"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "macro-tracker-db"
database_id = "8d47dc07-8f12-4869-825c-0cee87c206e9"
migrations_dir = "migrations"

[vars]
USDA_API_KEY = "73A0UOQRNjRewH4w9aLpYtkXCjQVoLY8BD7hIG4F"

